config/routes.rb
Rails.application.routes.draw do
  
 

  root 'sessions#new'
  
  get 'signup' => 'adms#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'signuprd' => 'rds#new'

 post  'rvas/mostrarTabla'
 resources :rvas
 get "created" => "rvas#create"
# get 'rvas/new'
 #get "metod" => "reservs#metodo"
 #get "created" => "reservs#create"
 
  resources :rvas do
    collection do
      get :new
      
    end
end
  
  

  
  resources :adms
  resources :rds do
      resources :canchas
  end
end

app/models/rva.rb
class Rva < ActiveRecord::Base
  belongs_to :cancha
end

app/controllers/rvas_controller.rb
class RvasController < ApplicationController
    
    def new
         @tipoCancha = params[:nombre]
         @id_cancha=params[:id_cancha]
         @hora=params[:hora]
         @fecha=params[:fecha]
         @valor=4000
         @cb=params[:pet_dog]
        
    end
    
    def create
    @reserva = Rva.new
    @nombre=params[:nombre]
    @telefono=params[:telefono]
    
    @reserva.telefono=@telefono
    @reserva.nombre=@nombre
    @reserva.fecha=params[:fecha]
    @reserva.hora=params[:hora]
    @reserva.valor=params[:valor]
    @reserva.cancha_id=params[:cancha_id]
       
    if @reserva.save
      #log_in @adm
      flash[:success] = "Reserva ingresada exitosamente"
       render 'new'
     else
      render 'new'
    end
  end
 
 
def index
     @rds=Rd.all
     
end
#probar to_i y probar todo eso
def mostrarTabla
    require 'time'
     @canchas = Cancha.where("rd_id = ?", params[:lista])
    #redirect a otro metodo con arreglo de canchas y dia seleccionado, otro metodo recibe el valor del dia
    
    require 'date'

date = Date.parse(params[:fecha10])
    
 @fecha=  date #Date.civil(*params[date].sort.map(&:last).map(&:to_i)) #params[:fecha]
   
   
   
   
   
   @reservas= Rva.where("fecha= ?", @fecha)
   #@reservita= Rva.all
  params["dropdown_cases"].each do |cases|
 @this_is_the_dropdown_value = cases.to_i
end
   

end
 
  
  
end

                                     

app/helpers/rvas_helper.rb
module RvasHelper
end

app/views/rvas/index.html.erb
<title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <style>
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 60%;
      height: 0%;
      margin: auto;
  }
  </style>
  <div class="container">
  <br>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

      <div class="item active">
        <img alt="Rails logo" src="/assets/rd1.jpg" />
        <div class="carousel-caption">
         
          <p><b>Recinto deportivo: Los dragones</b></p>
        </div>
      </div>

      <div class="item">
         <img alt="Rails logo" src="/assets/rd2.jpg" />
         
        <div class="carousel-caption">
         <p><b>Recinto deportivo: Las acacias</b></p>
        </div>
      </div>
    
      <div class="item">
         <img alt="Rails logo" src="/assets/rd1.jpg" />
        <div class="carousel-caption">
          <p><b>Recinto deportivo: Los robles</b></p>
        </div>
      </div>

      <div class="item">
       <img alt="Rails logo" src="/assets/rd2.jpg" />
        <div class="carousel-caption">
          <p>Recinto deportivo: Los dragones</p>
         
        </div>
      </div>
  
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<% names = Array.new
names[0]=2
names[1]=4
names[2]=48
%>
<%= names[2] %>


<%= form_tag({ controller: 'rvas', action: 'mostrarTabla' }, method: 'post') do %>
  
 <%= select_tag 'lista', options_from_collection_for_select(@rds.collect,:id, :nombre ) %>  
 


 
 
 
 
 

 

 
 
 
 <%= text_field_tag "fecha10", nil, :class => 'datepicker' %>
 

 <%= javascript_include_tag "application" %>
 
 
   
    
    
 <%= select_tag "dropdown_cases[]", options_for_select([ ["Bloque de 30 minutos", 1], ["Bloque de 1 hora", 2], ["Bloque de 1 hora y 30 minutos", 3], ["Bloque de 2 horas", 4], ["Bloque de 2 horas y 30 minutos", 5], ["Bloque de 3 horas", 6], ["Bloque de 3 horas y 30 minutos", 7]]) %>

<!-- Check Box -->
<!-- <%= check_box("puppy", "commands", {:multiple => true}, "sit", nil) %> 
<%= check_box("puppy", "commands", {:multiple => true}, "fetch", nil) %>
<%= check_box("puppy", "commands", {:multiple => true}, "roll_over", nil) %> -->
<!-- Fin Check Box -->

  <%= submit_tag "Buscar",class: "btn btn-primary" %>     


 
<% end %>

app/views/rvas/mostrarTabla.html.erb
<%= @this_is_the_dropdown_value  %>
  
 <% fechaSF= @fechaFormato %>
<% valor='rrrrr'%>
<%= fechaCF= @fecha %>
<% fechaCF %>
<%  #horas=['8','9','10','11','12','13','14','15','16','17','18','19','20'] %>
<%  horas=[8,9,10,11,12,13,14,15,16,17,18,19,20] %>
<% horasFormato= ['8:00:00','9:00:00','10:00:00','11:00:00','12:00:00','13:00:00','14:00:00','15:00:00','16:00:00','17:00:00','18:00:00','19:00:00','20:00:00'] %>
<%
vecHorasFormato=Array.new
m=0
horaInicioTabla2=8
horaFinalTabla2=20
while(horaInicioTabla2<=horaFinalTabla2)
 vecHorasFormato[m]=horaInicioTabla2
 m=m+1
 horaInicioTabla2=horaInicioTabla2+1
end
for i in 0..vecHorasFormato.length-1
%><%=vecHorasFormato[i] %>-<%
end
%>----------------------
<table id="t01">
    <tr>
        <td id="td02" ><p>Tipo Cancha</p></td>
    <td><b>8:00</b></td>
     <td><b>9:00</b></td>
     <td><b>10:00</b></td>
     <td><b>11:00</b></td>
     <td><b>12:00</b></td>
     <td><b>13:00</b></td>
     <td><b>14:00</b></td>
     <td><b>15:00</b></td>
     <td><b>16:00</b></td>
     <td><b>17:00</b></td>
     <td><b>18:00</b></td>
     <td><b>19:00</b></td>
     
  
  </tr>


  
  
<% @canchas.each do |c|
    %> <tr> <td><b><%= c.tipo %></td></b> <%
   cont=0
               
    
          @reservas.each do |r|
                
                  if r.cancha_id == c.id
                
                  cont += 1
                  end
            end
            
            
             %><%#para evitar casos de indice negativo y quitarle el valor extra q se le asigna   %><%
            if cont>=1
             cont=cont-1
              vec= Array.new(cont)
             else
              vec=Array.new(cont)
            end
            
            
           #sacando los ocupados
            
            cont=0
            @reservas.each do |r|
                 
                  if r.cancha_id == c.id
                  vec[cont]=r.hora.hour.to_i
                  cont +=  1
                  end
            end
           
            
            
            
            
            
 #ordenando la lista         
n = vec.length

for j in 0..n-1
    for i in 0..n - 2 - j
           if vec[i]>vec[i+1]
                tmp = vec[i]
                vec[i] = vec[i+1]
                vec[i+1] = tmp
          end
     end
end
            
            
            
           
           flag=0
           valor=0
             
 for i in 0..11
  for j in 0..vec.length-1
     if horas[i]==vec[j]
     flag=1
     valor= vec[j]
     end
  end
 if flag==1
 %><td><%= "Ocu" %></td><%
 else
 %><td><%= link_to 'valor',{ :controller => "rvas", :action => "new", :nombre => c.tipo,  :id_cancha => c.id, :hora => horasFormato[i], :fecha => fechaCF}%></td><%
 end
 flag=0
 valor=0
end                  
                  
                  
                 
           
%></tr><%
end %>
</table>
<%# desde aca %>
  
  
  
  <%# hasta aca iria el cosigo probado ayer %>
  
  
  
  
  
  
  
 <%# cambio  el anyterior es el que funciona
 %>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <%
   # a=[1,1,1,0,0,1,1,1,1,1,0,1]
   a=[1,1,1,1,1,1,1,1,1,1,1,1]
  # a=[0,0,1,1,1,1,1,0,0,1,0,0]
 # a=[1,1,1,0,0,1,1,1,1,1,0,1]
#a=[1,1,1,1,1,1,1,1,1,1,1,1]
#a=[0,0,0,0,0,0,0,0,0,0,0,0]
    
    bp=4
    b=0
    ct=11
    i=0
    c=2
    cent=0
    j=1
    f=0
    %><table id="t01">
    <tr>
        <td ><p>Tipo Cancha</p></td>
    <td><b>8:00-9:00 </b></td>
     <td><b> 9:00-10:00 </b></td>
     <td><b> 10:00-11:00 </b></td>
     <td><b>11:00-12:00</b></td>
     <td><b>12:00-13:00</b></td>
     <td><b>13:00-14:00</b></td>
     <td><b>14:00-15:00</b></td>
     <td><b>15:00-16:00</b></td>
     <td><b>16:00-17:00</b></td>
     <td><b>17:00-18:00</b></td>
     <td><b>18:00-19:00</b></td>
     <td><b>19:00-20:00</b></td>
     
  
  </tr>
    
    
 <%# ESTE FOR FORMA LAS FILAS DE LA TABLA, pro cada fila se reinicia el aux e i y se incrementa f %>
<% for f in 0..2 %> 
<%hi=0
hf=0%>
<% aux=0 
    i=0 %>
 <tr><td></td><%
 while i<=ct do
  
    if a[i]==0
        aux=i
        b=1
        c=0
          while c==0 do
           i=i+1
            if i<=ct
                     if a[i]==0
                          b=b+1
                     else
                          %> <% if b==1 %><td colspan=1 id="td02">ocupado</td>
                                <% elsif b==2 %><td colspan=2 id="td02">ocupado</td>
                                <% elsif b==3 %><td colspan=3 id="td02">ocupado</td>
                                <% elsif b==4 %><td colspan=4 id="td02">ocupado</td>
                                <% elsif b==5 %><td colspan=5 id="td02">ocupado</td>
                                <% elsif b==6 %><td colspan=6 id="td02">ocupado</td>
                                <% elsif b==7 %><td colspan=7 id="td02">ocupado</td>
                                <% elsif b==8 %><td colspan=8 id="td02">ocupado</td>
                                <% elsif b==9 %><td colspan=9 id="td02">ocupado</td>
                                <% elsif b==10 %><td colspan=10 id="td02">ocupado</td>
                                <% elsif b==11 %><td colspan=11 id="td02">ocupado</td>
                                <% elsif b==12 %><td colspan=12 id="td02">ocupado</td>
                                <%end%> <%
                           c=1
                           #ACA ASIGANMOS NUEVOS VALORES AL ARREGLO para dejarlos 0,1,
                            while(aux<i)
                              a[aux]=0
                              aux=aux+1
                            end
                     end
            else 
                    c=1
                    %> <% if b==1 %><td colspan=1 id="td02">ocupado</td>
                                <% elsif b==2 %><td colspan=2 id="td02">ocupado</td>
                                <% elsif b==3 %><td colspan=3 id="td02">ocupado</td>
                                <% elsif b==4 %><td colspan=4 id="td02">ocupado</td>
                                <% elsif b==5 %><td colspan=5 id="td02">ocupado</td>
                                <% elsif b==6 %><td colspan=6 id="td02">ocupado</td>
                                <% elsif b==7 %><td colspan=7 id="td02">ocupado</td>
                                <% elsif b==8 %><td colspan=8 id="td02">ocupado</td>
                                <% elsif b==9 %><td colspan=9 id="td02">ocupado</td>
                                <% elsif b==10 %><td colspan=10 id="td02">ocupado</td>
                                <% elsif b==11 %><td colspan=11 id="td02">ocupado</td>
                                <% elsif b==12 %><td colspan=12 id="td02">ocupado</td>
                                <%end%> <%
                             while(aux<i)
                              a[aux]=0
                              aux=aux+1
                            end
                    
           end
         
        end
         b=0
  elsif a[i]==1
     aux=i
     hi=i
     if bp==1
       i=i+1
      %><td id="td01" colspan="1">disponible</td><%
     else
                       if f>0
                           if i==0
                            %><td colspan="1"></td><%
                            a[i]=2
                            i=i+1
                            hi=i
                            aux=aux+1
                          elsif a[i-1]==2 || a[i-1]==0
                           %><td colspan="1"></td><%
                            a[i]=2
                            i=i+1
                            hi=i
                            aux=aux+1
                          else
                           i=i
                          end
                      end
       c=1
       h=1
       b=1
      
         while(c==1) do
          i=i+1
             if i<=ct
                if a[i]==1 || a[i]==2
                 h=h+1
                 b=b+1
                   if h==bp
                    hf=hi+bp
                   %><%=horasFormato[hi]%>*<%=horasFormato[hf]%><%
                       %><% if b==1 %><td colspan=1 id="td01">Disponible</td>
                                <% elsif b==2 %><td colspan=2 id="td01">Disponible</td>
                                <% elsif b==3 %><td colspan=3 id="td01">Disponible</td>
                                <% elsif b==4 %><td colspan=4 id="td01">Disponible</td>
                                <% elsif b==5 %><td colspan=5 id="td01">Disponible</td>
                                <% elsif b==6 %><td colspan=6 id="td01">Disponible</td>
                                <% elsif b==7 %><td colspan=7 id="td01">Disponible</td>
                                <% elsif b==8 %><td colspan=8 id="td01">Disponible</td>
                                <% elsif b==9 %><td colspan=9 id="td01">Disponible</td>
                                <% elsif b==10 %><td colspan=10 id="td01">Disponible</td>
                                <% elsif b==11 %><td colspan=11 id="td01">Disponible</td>
                                <% elsif b==12 %><td colspan=12 id="td01">Disponible</td>
                                <%end%> <%
                            
                    c=0
                    i=i+1
                           while(aux<i)
                              a[aux]=1
                              aux=aux+1
                            end
                   end
                   
                else
                         while(j<=b) do  
                            
                                 %><td colspan="1"> </td><%
                                 j=j+1
                         end
                          while(aux<i)
                              a[aux]=2
                              aux=aux+1
                            end
                 c=0
                end
             else
                               
                                 while(j<=b) do  
                            
                                 %><td colspan="1"> </td><%
                                 j=j+1
                               end
                             while(aux<i)
                              a[aux]=2
                              aux=aux+1
                            end
              c=0
             end
         end
      b=0
      h=0
      j=1
     end
    
     
     else a[i]==2
        aux=i
        b=1
        c=2
          while c==2 do
           i=i+1
            if i<=ct
                     if a[i]==2
                          b=b+1
                     else
                           while(j<=b) do  
                            
                                 %><td colspan="1"> </td><%
                                 j=j+1
                         end
                           c=0
                           #ACA ASIGANMOS NUEVOS VALORES AL ARREGLO para dejarlos 0,1,
                            while(aux<i)
                              a[aux]=2
                              aux=aux+1
                            end
                     end
            else 
                    c=0
                        while(j<=b) do  
                            
                                 %><td colspan="1"> </td><%
                                 j=j+1
                         end
                             while(aux<i)
                              a[aux]=2
                              aux=aux+1
                            end
                    
           end
         
        end
         b=0
         j=1
   
  end
  
 end
%>
<%= button_to "Nueva busqueda", rvas_path, method: :get %>
     
   
  %></tr>
        
        
        
    <% end %>
  
  
  
  
  
  
  
  
  
  
 
  
     

  </table>
 
 
 
 
 
 
 
 
 
 
 
 
 
 

 

app/views/rvas/new.html.erb
<table>
<tr>
<td>

<h4>Ingresar Nueva Reserva </h4>
     <p>Cancha: </p> 
     <div class="panel panel-default"> <%=  @tipoCancha%></div> 
    <p>Fecha: </p> 
    <div class="panel panel-default"><%= @fecha%></div>
    <p> Hora:</p> 
    <div class="panel panel-default"><%= @hora%></div>
    <p>Total:</p>
    <div class="panel panel-default"><%= @valor%></div>
  

     
     
     

      
<%= form_tag(created_path ,:id =>"nomtel", :method=> "get") do %>

    <p>Nombre: <%= text_field_tag ("nombre")%></p> 
    <p>Telefono:  <%= text_field_tag("telefono")%></p> 
    
    
   
    
    <%= hidden_field_tag "fecha", @fecha %>
    <%= hidden_field_tag "hora", @hora %>
    <%= hidden_field_tag "valor", @valor %>
    <%= hidden_field_tag "cancha_id", @id_cancha %>


<%= submit_tag("Enviar") %>

<% end %>
</td>
<td><img alt="Rails logo" src="/assets/recintodep.jpg" /></td>
</tr>
</table>