config/routes.rb
Rails.application.routes.draw do
  
 

  root 'sessions#new'
  
  get 'signup' => 'adms#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'signuprd' => 'rds#new'

 post  'rvas/mostrarTabla'
 resources :rvas
 get "created" => "rvas#create"
# get 'rvas/new'
 #get "metod" => "reservs#metodo"
 #get "created" => "reservs#create"
 
  resources :rvas do
    collection do
      get :new
      
    end
end
  
  

  
  resources :adms
  resources :rds do
      resources :canchas
  end
end

app/models/rd.rb
class Rd < ActiveRecord::Base
    has_many :canchas, dependent: :destroy
     validates :nombre, presence: true, length: { maximum: 50 }
     validates :direccion, presence: true, length: { maximum: 50 }
     validates :responsable, presence: true, length: { maximum: 50 }
end

app/controllers/rds_controller.rb
class RdsController < ApplicationController
before_action :logged_in_adm, only: [:index, :edit, :update, :create]   
    
    
  def new
    @rd= Rd.new
  end
  
   def create
    @rd = Rd.new(rd_params)    
    if @rd.save
      #log_in @adm
      flash[:success] = "Recinto deportivo creado exitosamente"
       redirect_to new
    else
      render 'new'
    end
  end
  
   def index
   @rds= Rd.all
end

def destroy
    Rd.find(params[:id]).destroy
    flash[:success] = "Recinto deportivo Borrado"
    redirect_to rds_url
  end
  
  def show
  @rd=Rd.find(params[:id])
  @canchas=@rd.canchas
  
end
def edit
    @rd = Rd.find(params[:id])
  end

def update
    @rd = Rd.find(params[:id])
    if @rd.update_attributes(rd_params)
      flash[:success] = "Recinto deportivo actualizado correctamente"
      redirect_to new
    else
      render 'edit'
    end
  end
  
def mostrarLista
   @rds=Rd.all
end
  
def mostrarTabla
  
     @canchas = Cancha.where("rd_id = ?", params[:lista])
    #redirect a otro metodo con arreglo de canchas y dia seleccionado, otro metodo recibe el valor del dia
    @fecha=  Date.civil(*params[:fecha].sort.map(&:last).map(&:to_i))
   @reservas= Rva.where("fecha= ?", @fecha)
   #@reservita= Rva.all
   
   
   #@fecha2=  params[:fecha]
   
end
  
  
 private

    def rd_params
      params.require(:rd).permit(:nombre, :direccion, :responsable)
    end
    
    def logged_in_adm #evita que desde afuera modifiquen#
      unless logged_in?
        flash[:danger] = "Por favor ingrese."
        redirect_to login_url
      end
    end
    
end

app/helpers/rds_helper.rb
module RdsHelper
end

app/views/rds/edit.html.erb
<h3>Actualizar Recinto deportivo</h3>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@rd) do |f| %>
    <%= render 'shared/error_messages',object: f.object %> 

      <%= f.label :Nombre %>
    <%= f.text_field :nombre, class: 'form-control' %>
    
    <%= f.label :Dirección %>
    <%= f.text_field :direccion, class: 'form-control' %>
    
    <%= f.label :Responsable %>
    <%= f.text_field :responsable, class: 'form-control' %>


      <%= f.submit "Guardar", class: "btn btn-primary" %>
    <% end %>

    
  </div>
</div>

app/views/rds/index.html.erb
<div class="panel panel-default">
  <div class="panel-body">
      <div class="container">
   
   <h5> <%= link_to "Crear Nuevo Recinto Deportivo", signuprd_path %></h5>
   
 </div>
      
  </div>
</div>
 
 


<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Dirección</th>
      <th>Responsable</th>
      <th>Acciones</th>
      <th>Canchas</th>
    </tr>
  </thead>
  <tbody>
      <% @rds.each do |rd| %>
                        <tr>
                          <td> <%= rd.nombre%> </td>
                          <td> <%= rd.direccion%> </td>
                          <td> <%= rd.responsable %> </td>
                          <td><%= link_to "Editar", edit_rd_path(rd)  %>
                          
                          <%= link_to "Eliminar", rd, method: :delete,
                                  data: { confirm: "¿Está seguro de eliminar?" } %> </td>
                           <td> <%= link_to "ver canchas", rd %></td>
                       </tr>
    
      <% end %>
  </tbody>
</table>

app/views/rds/mostrarLista.html.erb
<table>
<div class="panel panel-default">
<div class="row" >
  <div class="col-sm-4">
<%= form_tag({ controller: 'rds', action: 'mostrarTabla' }, method: 'post') do %>
 <tr><td>Recinto deportivo</td><td>Fecha</td></tr> 
 <tr><td><%= select_tag 'lista', options_from_collection_for_select(@rds.collect,:id, :nombre ) %>  </td>
 <td><%= date_select("fecha", 'valoresFecha', :start_year => Date.current.year , )%></td></tr> 
  <td><%= check_box_tag 'accept'%></td> yyyyyyyyyyy
 
  <tr><td><%= submit_tag "Buscar",class: "btn btn-primary" %></td>  </tr>      


 
<% end %></div></div>

</div>

</table>


GHAGHSGHAGHSGHSAGHGHHG

app/views/rds/mostrarTabla.html.erb
 <% fechaSF= @fechaFormato %>
<% fechaSF %>
<% fechaCF= @fecha %>
<% fechaCF %> 
<%  #horas=['8','9','10','11','12','13','14','15','16','17','18','19','20'] %>
<%  horas=[8,9,10,11,12,13,14,15,16,17,18,19,20] %>

<% horasFormato= ['8:00:00','9:00:00','10:00:00','11:00:00','12:00:00','13:00:00','14:00:00','15:00:00','16:00:00','17:00:00','18:00:00','19:00:00','20:00:00'] %>
<table style="width:100%">
    <tr>
        <td>Tipo Canchaaaaa</td>
    <td>8:00-9:00</td>
    <td>9:00-10:00</td> 
    <td>10:00-11:00</td>
     <td>11:00-12:00</td>
    <td>12:00-13:00</td> 
    <td>13:00-14:00</td>
     <td>14:00-15:00</td>
    <td>15:00-16:00</td> 
    <td>16:00-17:00</td>
     <td>-17:00-18:00</td>
    <td>18:00-19:00</td> 
    <td>19:00-20:00</td>
  </tr>
<% @canchas.each do |c|
    %> <tr> <td><%= c.tipo %></td> <%
   cont=0
  
    
          @reservas.each do |r|
                 
                  if r.cancha_id == c.id
                 
                  cont += 1
                  end
            end
            
            
             %><%#para evitar casos de indice negativo y quitarle el valor extra q se le asigna   %><%
            if cont>=1
             cont=cont-1
              vec= Array.new(cont)
             else
              vec=Array.new(cont)
            end
            
            
           
             %><% cont  %><%
            cont=0
            @reservas.each do |r|
                 
                  if r.cancha_id == c.id
                  vec[cont]=r.hora.hour.to_i
                  cont +=  1
                  end
            end
           
            
            
            
            
            
          
n = vec.length

for j in 0..n-1
    for i in 0..n - 2 - j
           if vec[i]>vec[i+1]
                tmp = vec[i]
                vec[i] = vec[i+1]
                vec[i+1] = tmp
          end
     end
end
            
            
            
           
           flag=0
           valor=0
             
 for i in 0..11
  for j in 0..vec.length-1
     if horas[i]==vec[j]
     flag=1
     valor= vec[j]
     end
  end
 if flag==1
 %><td><%= "Ocupado" %></td><%
 else
 %><td><%= link_to 'disponible',{ :controller => "rvas", :action => "new", :nombre => c.tipo, :id_cancha => c.id, :hora => horasFormato[i], :fecha => fechaCF}%></td><%
 end
 flag=0
 valor=0
end                  
                  
                  
           
           
%></tr><%
end %>


 </table>
 
  
 
 

 
 

app/views/rds/new.html.erb
<h1>Ingresar Nuevo Recinto deportivo</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@rd) do |f| %>
     <%= render 'shared/error_messages',object: f.object %>
     
      <%= f.label :Nombre %>
      <%= f.text_field :nombre, class: 'form-control' %>
      
      <%= f.label :Direccion %>
      <%= f.text_field :direccion, class: 'form-control' %>
      
      <%= f.label :Responsable %>
      <%= f.text_field :responsable, class: 'form-control' %>
      
      
     
      <%= f.submit "Aceptar", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/rds/show.html.erb
    
<h2>Recinto deportivo:  <%=@rd.nombre %></h2>

 
     
<table>
  <thead>
    <tr>
      <th>Tipo de Cancha</th>
      <th>Estado</th>
      <th>Acciones</th>
      </tr>
  </thead>
  <tbody>
        <% @canchas.each do |f|%>
                        <tr>
                          <td><%= f.tipo %> </td>
                          <td><%= f.estado %></td>
                          <td>  
                          <%= link_to 'Eliminar', [f.rd, f],
               method: :delete,
               data: { confirm: 'Esta seguro de eliminar?' } %> </td>
      <%end %>    
                       </tr>
    
             
  </tbody>
</table>
 
<div class="row" >
  <div class="col-sm-4">
    

<h2>Ingresar Nueva Cancha</h2>
    <%= form_for([@rd,@rd.canchas.build]) do |f| %>
    
     
      <%= f.label :tipo %>
      <%= f.text_field :tipo, class: 'form-control' %> 
      
      <%= f.label :estado %>
      <%= f.text_field :estado, class: 'form-control' %> 

      <%= f.submit "Aceptar", class: "btn btn-primary" %>
    <% end %>  
 </div>
</div>        
 
    

 