config/routes.rb
Rails.application.routes.draw do
  
 

  root 'sessions#new'
  
  get 'signup' => 'adms#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'signuprd' => 'rds#new'

 post  'rvas/mostrarTabla'
 resources :rvas
 get "created" => "rvas#create"
# get 'rvas/new'
 #get "metod" => "reservs#metodo"
 #get "created" => "reservs#create"
 
  resources :rvas do
    collection do
      get :new
      
    end
end
  
  

  
  resources :adms
  resources :rds do
      resources :canchas
  end
end

app/models/adm.rb
class Adm < ActiveRecord::Base
    before_save { self.email = email.downcase }
  validates :nombre, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/models/cancha.rb
class Cancha < ActiveRecord::Base
  belongs_to :rd
  has_many :horarioreservas, dependent: :destroy
  validates :rd_id, presence: true
end

app/models/rd.rb
class Rd < ActiveRecord::Base
    has_many :canchas, dependent: :destroy
     validates :nombre, presence: true, length: { maximum: 50 }
     validates :direccion, presence: true, length: { maximum: 50 }
     validates :responsable, presence: true, length: { maximum: 50 }
end

app/models/reserv.rb
class Reserv < ActiveRecord::Base
  belongs_to :cancha
end

app/models/reserva.rb
class Reserva < ActiveRecord::Base
end

app/models/rva.rb
class Rva < ActiveRecord::Base
  belongs_to :cancha
end

app/controllers/adms_controller.rb
class AdmsController < ApplicationController
  before_action :logged_in_adm, only: [:index, :edit, :update, :new, :create]
  before_action :correct_adm,   only: [:edit, :update]
  before_action :palla
  def new
    @adm= Adm.new
  end
  
  def index
    @adms = Adm.all
  end
  
   def destroy
    Adm.find(params[:id]).destroy
    flash[:success] = "Administrador Borrado"
    redirect_to adms_url
  end
  
  
  def show
    @adm = Adm.find(params[:id])
  end
  
  def create
    @adm = Adm.new(adm_params)    
    if @adm.save
      #log_in @adm
      flash[:success] = "Adminstrador creado exitosamente"
       redirect_to new
    else
      render 'new'
    end
  end
  
  def edit
    @adm = Adm.find(params[:id])
  end

def update
    @adm = Adm.find(params[:id])
    if @adm.update_attributes(adm_params)
      flash[:success] = "Perfil actualizado correctamente"
      redirect_to @adm
    else
      render 'edit'
    end
  end
  
  private

    def adm_params
      params.require(:adm).permit(:nombre, :email, :roles,:password,
                                   :password_confirmation)
    end
    
    def logged_in_adm #evita que desde afuera modifiquen#
      unless logged_in?
        flash[:danger] = "Por favor ingrese."
        redirect_to login_url
      end
    end
    
     def correct_adm #evita que desde adentro modifiquen#
      @adm = Adm.find(params[:id])
      redirect_to(root_url) unless @adm == current_adm
    end
    
     def palla
      if logged_in?
    @current_user = current_adm
    if @current_user.roles==1
      redirect_to(rvas_path)
    end
  end
end
end

app/controllers/canchas_controller.rb
class CanchasController < ApplicationController
 

 def create
    @rd=Rd.find(params[:rd_id])
    @cancha= @rd.canchas.create(cancha_params)
    if @cancha.save
      
      flash[:success] = "cancha creado exitosamente"
       redirect_to rds_url
    else
      render 'new'
    end
  end
 

  


def destroy
    Cancha.find(params[:id]).destroy
    flash[:success] = "cancha Borrada"
    redirect_to rds_url
  end





def edit
    @cancha = Cancha.find(params[:id])
  end
  
  

def update
    @cancha = Cancha.find(params[:id])
    if @cancha.update_attributes(cancha_params)
      flash[:success] = "cancha actualizado correctamente"
      render 'edit'
       
    else
      render 'edit'
    end
  end
  
  private

    def cancha_params
      params.require(:cancha).permit(:tipo, :estado)
    end
end

app/controllers/rds_controller.rb
class RdsController < ApplicationController
before_action :logged_in_adm, only: [:index, :edit, :update, :create]   
    
    
  def new
    @rd= Rd.new
  end
  
   def create
    @rd = Rd.new(rd_params)    
    if @rd.save
      #log_in @adm
      flash[:success] = "Recinto deportivo creado exitosamente"
       redirect_to new
    else
      render 'new'
    end
  end
  
   def index
   @rds= Rd.all
end

def destroy
    Rd.find(params[:id]).destroy
    flash[:success] = "Recinto deportivo Borrado"
    redirect_to rds_url
  end
  
  def show
  @rd=Rd.find(params[:id])
  @canchas=@rd.canchas
  
end
def edit
    @rd = Rd.find(params[:id])
  end

def update
    @rd = Rd.find(params[:id])
    if @rd.update_attributes(rd_params)
      flash[:success] = "Recinto deportivo actualizado correctamente"
      redirect_to new
    else
      render 'edit'
    end
  end
  
def mostrarLista
   @rds=Rd.all
end
  
def mostrarTabla
  
     @canchas = Cancha.where("rd_id = ?", params[:lista])
    #redirect a otro metodo con arreglo de canchas y dia seleccionado, otro metodo recibe el valor del dia
    @fecha=  Date.civil(*params[:fecha].sort.map(&:last).map(&:to_i))
   @reservas= Rva.where("fecha= ?", @fecha)
   #@reservita= Rva.all
   
   
   #@fecha2=  params[:fecha]
   
end
  
  
 private

    def rd_params
      params.require(:rd).permit(:nombre, :direccion, :responsable)
    end
    
    def logged_in_adm #evita que desde afuera modifiquen#
      unless logged_in?
        flash[:danger] = "Por favor ingrese."
        redirect_to login_url
      end
    end
    
end

app/controllers/reservs_controller.rb
class ReservsController < ApplicationController
    def index
end
     def create
        @reserva=Reservs.new
        @nombre=params[:nombre]
        @telefono=params[:telefono]
       
        @reserva.telefono=@telefono
        @reserva.nombre=@nombre
         
         
        @reserva.cancha_id=params[:canchaid]
        @reserva.hora=params[:hora]
        
        
        @reserva.save
       
         render :text => params[:hora1].inspect
       
    
    
    end
    
    def metodo
        
        
        @id = params[:id]
        @hora = params[:hora]
        
    end
end

app/controllers/rvas_controller.rb
class RvasController < ApplicationController
    
    def new
         @tipoCancha = params[:nombre]
         @id_cancha=params[:id_cancha]
         @hora=params[:hora]
         @fecha=params[:fecha]
         @valor=4000
         @cb=params[:pet_dog]
        
    end
    
    def create
    @reserva = Rva.new
    @nombre=params[:nombre]
    @telefono=params[:telefono]
    
    @reserva.telefono=@telefono
    @reserva.nombre=@nombre
    @reserva.fecha=params[:fecha]
    @reserva.hora=params[:hora]
    @reserva.valor=params[:valor]
    @reserva.cancha_id=params[:cancha_id]
       
    if @reserva.save
      #log_in @adm
      flash[:success] = "Reserva ingresada exitosamente"
       render 'new'
     else
      render 'new'
    end
  end
 
 
def index
     @rds=Rd.all
     
end
#probar to_i y probar todo eso
def mostrarTabla
    require 'time'
     @canchas = Cancha.where("rd_id = ?", params[:lista])
    #redirect a otro metodo con arreglo de canchas y dia seleccionado, otro metodo recibe el valor del dia
    
    require 'date'

date = Date.parse(params[:fecha10])
    
 @fecha=  date #Date.civil(*params[date].sort.map(&:last).map(&:to_i)) #params[:fecha]
   
   
   
   
   
   @reservas= Rva.where("fecha= ?", @fecha)
   #@reservita= Rva.all
  params["dropdown_cases"].each do |cases|
 @this_is_the_dropdown_value = cases.to_i
end
   

end
 
  
  
end

                                     

app/helpers/adms_helper.rb
module AdmsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def formatoHora(hora)
        minutos=0
        format("%02d:%02d", hora, minutos)
        
    end
end

app/helpers/canchas_helper.rb
module CanchasHelper
end

app/helpers/rds_helper.rb
module RdsHelper
end

app/helpers/reserva2_helper.rb
module Reserva2Helper
end

app/helpers/reserva3_helper.rb
module Reserva3Helper
end

app/helpers/reservs_helper.rb
module ReservsHelper
end

app/helpers/rvas_helper.rb
module RvasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(adm)
    session[:adm_id] = adm.id
    end
    
    def current_adm
    @current_adm ||= Adm.find_by(id: session[:adm_id])
   end
   
   def logged_in?
    !current_adm.nil?
  end
  
   def log_out
    session.delete(:adm_id)
    @current_adm = nil
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
     
      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
   
    <%= link_to "Municipalidad de la Reina", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        
         <% @current_user = current_adm %>
                  
       
       <% if logged_in? %>
       
       <% if @current_user.roles==0%>
        <li><%= link_to "Mi perfil", edit_adm_path(current_adm)  %></li>
      <%end%>
        <li><%= link_to "Salir", logout_path, method: :delete  %></li>
        
     
      <% end %>
      </ul>
    </nav>
                           
  </div>
  
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    
    
     
    
    
    
            <% @current_user = current_adm %>
                  <% if logged_in? && @current_user.roles==0%>
                         <div class="container">
                          <h3></h3>
                          <ul class="nav nav-tabs">
                            
                            <li><%= link_to "Administrador", adms_path %></li>
                            <li><%= link_to "Recintos deportivos", rds_path %></li>
                            
                          
                            
                            <li><%= link_to "Reserva", rvas_path %></li>
                            
                            <li><a href="#">Facturación</a></li>
                          </ul>
                        </div>
                  <% end %>
    <%= render 'layouts/header' %>



    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
        
      <% end %>
      
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>